# frozen_string_literal: true

module Panko
  module CodeGen
    # Cache storage and runtime dispatch for ActiveRecord attribute writing.
    #
    # Owns the parallel cache arrays (+col+, +key+, +wtr+, +dir+) built
    # after the first-pass type resolution, and dispatches to the
    # appropriate generated method on +klass+ based on record state.
    #
    # All per-attribute iteration is generated by the {Compiler} —
    # this class contains no attribute loops.
    #
    # One instance per generated class, created by the {Compiler}.
    class ActiveRecordAttributesWriter
      # Column index per attribute (parallel array).
      # @return [Array<Integer>, nil]
      attr_reader :col

      # JSON key per attribute (parallel array).
      # @return [Array<String>, nil]
      attr_reader :key

      # Cached ValuesWriter per attribute (parallel array).
      # @return [Array<Object, nil>, nil]
      attr_reader :wtr

      # Whether each attribute supports direct push_value (parallel array).
      # @return [Array<Boolean>, nil]
      attr_reader :dir

      # The plain attributes in order, used by generated code.
      # @return [Array<Panko::Attribute>]
      attr_reader :attrs

      # @param attrs [Array<Panko::Attribute>] plain attributes in order
      # @param klass [Class] the generated class (for calling generated methods)
      def initialize(attrs:, klass:)
        @attrs = attrs
        @klass = klass
        @tl_rs_key = :"_panko_rs_#{object_id}"
        @col = nil
        @key = nil
        @wtr = nil
        @dir = nil
        @caches_ready = false
        @mutex = Mutex.new
      end

      # Dispatches attribute writing based on runtime record state.
      # Calls the appropriate generated method on +klass+.
      #
      # @param object [ActiveRecord::Base] the AR record
      # @param writer [Oj::StringWriter] the output writer
      # @param filter_mask [FilterMask] never nil — use FilterMask::EMPTY for unfiltered
      # @return [void]
      def write(object, writer, filter_mask)
        rs = record_state
        handle_class_change(rs) if rs.setup(object)
        attr_mask = filter_mask.attrs

        if rs.is_indexed_row && !rs.has_attributes_hash
          if @caches_ready
            @klass._write_indexed_cached(rs.row, writer, attr_mask)
          else
            @klass._write_indexed_first_pass(self, rs, writer, attr_mask)
            build_caches!(rs)
          end
        else
          @klass._write_ar_fallback(self, rs, writer, attr_mask)
        end
      end

      # Dispatches attribute writing to a Ruby Hash based on record state.
      # Same dispatch as +write+ but calls +_hash+ method variants.
      #
      # @param object [ActiveRecord::Base] the AR record
      # @param result [Hash] the output hash to populate
      # @param filter_mask [FilterMask] never nil — use FilterMask::EMPTY for unfiltered
      # @return [void]
      def write_hash(object, result, filter_mask)
        rs = record_state
        handle_class_change(rs) if rs.setup(object)
        attr_mask = filter_mask.attrs

        unless rs.is_indexed_row && !rs.has_attributes_hash
          @klass._write_ar_fallback_hash(self, rs, result, attr_mask)
          return
        end

        unless @caches_ready
          @klass._write_indexed_first_pass_hash(self, rs, result, attr_mask)
          build_caches!(rs)
          return
        end

        @klass._write_indexed_cached_hash(rs.row, result, attr_mask)
      end

      # Builds the parallel cache arrays from the current RecordState.
      # Thread-safe via double-checked locking.
      #
      # @param rs [RecordState] a record state with populated column_indexes
      # @return [void]
      def build_caches!(rs)
        return if @caches_ready

        @mutex.synchronize do
          return if @caches_ready

          ci = rs.column_indexes
          n = @attrs.length

          @col = Array.new(n) { |i| ci[@attrs[i].name] }
          @key = Array.new(n) { |i| @attrs[i].name_for_serialization }
          @wtr = Array.new(n) { |i| @attrs[i].cached_writer }
          @dir = Array.new(n) { |i| @attrs[i].cached_writer&.nil_safe_push? || false }
          @caches_ready = true
        end
      end

      # @return [Boolean]
      def caches_ready?
        @caches_ready
      end

      # Invalidates cached types/writers and resolves AR column aliases
      # when the record class changes between calls.
      def handle_class_change(rs)
        @caches_ready = false
        @col = nil

        record_class = rs.last_record_class
        return unless record_class.respond_to?(:attribute_aliases)

        aliases_hash = record_class.attribute_aliases
        has_aliases = !aliases_hash.empty?

        @attrs.each do |attr|
          attr.invalidate!
          next unless has_aliases

          aliased_value = aliases_hash[attr.name]
          if aliased_value.present?
            attr.alias_name = attr.name
            attr.name = aliased_value
          end
        end
      end

      # Returns the thread-local RecordState for this writer.
      #
      # @return [Panko::Engine::AttributesWriter::ActiveRecord::RecordState]
      def record_state
        Thread.current[@tl_rs_key] ||=
          Panko::Engine::AttributesWriter::ActiveRecord::RecordState.new
      end
    end
  end
end
