# frozen_string_literal: true

module Panko
  module CodeGen
    # Cache storage and runtime dispatch for ActiveRecord attribute writing.
    #
    # Owns the parallel cache arrays (+col+, +key+, +wtr+, +dir+) built
    # after the first-pass type resolution, and dispatches to the
    # appropriate generated method on +klass+ based on record state.
    #
    # All per-attribute iteration is generated by the {Compiler} —
    # this class contains no attribute loops.
    #
    # One instance per generated class, created by the {Compiler}.
    class ActiveRecordAttributesWriter
      # Column index per attribute (parallel array).
      # @return [Array<Integer>, nil]
      attr_reader :col

      # JSON key per attribute (parallel array).
      # @return [Array<String>, nil]
      attr_reader :key

      # Cached ValuesWriter per attribute (parallel array).
      # @return [Array<Object, nil>, nil]
      attr_reader :wtr

      # Whether each attribute supports direct push_value (parallel array).
      # @return [Array<Boolean>, nil]
      attr_reader :dir

      # The plain attributes in order, used by generated code.
      # @return [Array<Panko::Attribute>]
      attr_reader :attrs

      # @param attrs [Array<Panko::Attribute>] plain attributes in order
      # @param klass [Class] the generated class (for calling generated methods)
      def initialize(attrs:, klass:)
        @attrs = attrs
        @klass = klass
        @tl_rs_key = :"_panko_rs_#{object_id}"
        @col = nil
        @key = nil
        @wtr = nil
        @dir = nil
        @caches_ready = false
        @mutex = Mutex.new
      end

      # Dispatches attribute writing based on runtime record state.
      # Calls the appropriate generated method on +klass+.
      #
      # @param object [ActiveRecord::Base] the AR record
      # @param writer [Oj::StringWriter, Panko::ObjectWriter] the output writer
      # @param filter_mask [FilterMask, nil] nil for unfiltered
      # @return [void]
      def write(object, writer, filter_mask)
        rs = record_state
        rs.setup(object)

        if rs.is_indexed_row && !rs.has_attributes_hash
          if @caches_ready
            if filter_mask
              @klass._write_indexed_cached_filtered(rs.row, writer, filter_mask.attrs)
            else
              @klass._write_indexed_cached(rs.row, writer)
            end
          else
            @klass._write_indexed_first_pass(self, rs, writer)
            build_caches!(rs)
          end
        elsif filter_mask
          @klass._write_ar_fallback_filtered(self, rs, writer, filter_mask.attrs)
        else
          @klass._write_ar_fallback(self, rs, writer)
        end
      end

      # Builds the parallel cache arrays from the current RecordState.
      # Thread-safe via double-checked locking.
      #
      # @param rs [RecordState] a record state with populated column_indexes
      # @return [void]
      def build_caches!(rs)
        return if @caches_ready

        @mutex.synchronize do
          return if @caches_ready

          ci = rs.column_indexes
          n = @attrs.length

          @col = Array.new(n) { |i| ci[@attrs[i].name] }
          @key = Array.new(n) { |i| @attrs[i].name_for_serialization }
          @wtr = Array.new(n) { |i| @attrs[i].cached_writer }
          @dir = Array.new(n) { |i| @attrs[i].cached_writer&.nil_safe_push? || false }
          @caches_ready = true
        end
      end

      # @return [Boolean]
      def caches_ready?
        @caches_ready
      end

      # Returns the thread-local RecordState for this writer.
      #
      # @return [Panko::Engine::AttributesWriter::ActiveRecord::RecordState]
      def record_state
        Thread.current[@tl_rs_key] ||=
          Panko::Engine::AttributesWriter::ActiveRecord::RecordState.new
      end
    end
  end
end
