# frozen_string_literal: true

module Panko
  module CodeGen
    # Runtime dispatch for ActiveRecord attribute writing.
    #
    # After the first-pass type resolution, populates per-attribute class
    # ivars (+@_col_0+, +@_dir_0+, +@_wtr_0+, ...) on the generated class
    # so the hot-path generated code uses direct ivar reads with no array
    # indirection.
    #
    # All per-attribute iteration is generated by the {Compiler} —
    # this class contains no attribute loops.
    #
    # One instance per generated class, created by the {Compiler}.
    class ActiveRecordAttributesWriter
      # The plain attributes in order, used by generated code.
      # @return [Array<Panko::Attribute>]
      attr_reader :attrs

      # @param attrs [Array<Panko::Attribute>] plain attributes in order
      # @param klass [Class] the generated class (for calling generated methods)
      def initialize(attrs:, klass:)
        @attrs = attrs
        @klass = klass
        @tl_rs_key = :"_panko_rs_#{object_id}"
        @caches_ready = false
        @mutex = Mutex.new
        stamp_attr_ivars!
      end

      # Dispatches attribute writing based on runtime record state.
      # Calls the appropriate generated method on +klass+.
      #
      # @param object [ActiveRecord::Base] the AR record
      # @param writer [Oj::StringWriter] the output writer
      # @param filter_mask [FilterMask] never nil — use FilterMask::EMPTY for unfiltered
      # @return [void]
      def write(object, writer, filter_mask)
        rs = record_state
        handle_class_change(rs) if rs.setup(object)
        attr_mask = filter_mask.attrs

        if rs.is_indexed_row && !rs.has_attributes_hash
          if @caches_ready
            @klass._write_indexed_cached(rs.row, writer, attr_mask)
          else
            @klass._write_indexed_first_pass(self, rs, writer, attr_mask)
            build_caches!(rs)
          end
        else
          @klass._write_ar_fallback(self, rs, writer, attr_mask)
        end
      end

      # Dispatches attribute writing to a Ruby Hash based on record state.
      # Same dispatch as +write+ but calls +_hash+ method variants.
      #
      # @param object [ActiveRecord::Base] the AR record
      # @param result [Hash] the output hash to populate
      # @param filter_mask [FilterMask] never nil — use FilterMask::EMPTY for unfiltered
      # @return [void]
      def write_hash(object, result, filter_mask)
        rs = record_state
        handle_class_change(rs) if rs.setup(object)
        attr_mask = filter_mask.attrs

        unless rs.is_indexed_row && !rs.has_attributes_hash
          @klass._write_ar_fallback_hash(self, rs, result, attr_mask)
          return
        end

        unless @caches_ready
          @klass._write_indexed_first_pass_hash(self, rs, result, attr_mask)
          build_caches!(rs)
          return
        end

        @klass._write_indexed_cached_hash(rs.row, result, attr_mask)
      end

      # Stamps +@_attr_#{i}+ on the generated class, one per attribute, so
      # the unrolled +_write_ar_fallback+ else branch can read the
      # {Panko::Attribute} by direct ivar instead of +aw.attrs[i]+.
      #
      # Runs once at class build time — these ivars never change (the
      # {Panko::Attribute} object is reused; its +name+ may be rewritten by
      # {#handle_class_change}, which is why the generated code reads
      # +@_attr_#{i}.name+ at call time via +rs.read_attribute+).
      #
      # Order matters for object shape stability: this stamping, the lazy
      # +@_col_#{i}+ / +@_wtr_#{i}+ / +@_dir_#{i}+ in {#build_caches!}, and
      # any per-class ivars set by the Compiler must land in a consistent
      # order across every generated class so they share a single shape
      # tree in the Ruby VM.
      #
      # @return [void]
      def stamp_attr_ivars!
        @attrs.each_with_index do |attr, i|
          @klass.instance_variable_set(:"@_attr_#{i}", attr)
        end
      end

      # Sets per-attribute class ivars (+@_col_i+, +@_dir_i+, +@_wtr_i+) on
      # the generated class so the hot-path code uses direct ivar reads.
      # Thread-safe via double-checked locking.
      #
      # @param rs [RecordState] a record state with populated column_indexes
      # @return [void]
      def build_caches!(rs)
        return if @caches_ready

        @mutex.synchronize do
          return if @caches_ready

          ci = rs.column_indexes

          @attrs.each_with_index do |attr, i|
            @klass.instance_variable_set(:"@_col_#{i}", ci[attr.name])
            @klass.instance_variable_set(:"@_wtr_#{i}", attr.cached_writer)
            @klass.instance_variable_set(:"@_dir_#{i}", attr.cached_writer&.nil_safe_push? || false)
          end
          @caches_ready = true
        end
      end

      # @return [Boolean]
      def caches_ready?
        @caches_ready
      end

      # Invalidates cached types/writers and resolves AR column aliases
      # when the record class changes between calls.
      def handle_class_change(rs)
        @caches_ready = false

        record_class = rs.last_record_class
        return unless record_class.respond_to?(:attribute_aliases)

        aliases_hash = record_class.attribute_aliases
        has_aliases = !aliases_hash.empty?

        @attrs.each do |attr|
          attr.invalidate!
          next unless has_aliases

          aliased_value = aliases_hash[attr.name]
          if aliased_value.present?
            attr.alias_name = attr.name
            attr.name = aliased_value
          end
        end
      end

      # Returns the thread-local RecordState for this writer.
      #
      # @return [Panko::Engine::AttributesWriter::ActiveRecord::RecordState]
      def record_state
        Thread.current[@tl_rs_key] ||=
          Panko::Engine::AttributesWriter::ActiveRecord::RecordState.new
      end
    end
  end
end
