# frozen_string_literal: true

module Panko
  # Nested (not scoped +Panko::CodeGen+) form on purpose: this file is
  # loaded first — both by the gem entrypoint and standalone by the
  # gemspec — so it must vivify +Panko+ itself; every other file then
  # reopens the namespace with the scoped form.
  module CodeGen
    VERSION = "0.1.0"

    # Project name as it appears in user-facing artifacts. Spliced into the
    # +# Generated by ...+ line of every Dumped (and in-memory Compiled)
    # file's header banner per +docs/dumping.md § Dumped file shape+. Held
    # as a single constant so the rename to Panko (planned for the gem's
    # absorption into the Panko ecosystem per +CLAUDE.md § What this
    # project is+) is a single edit.
    GENERATOR_NAME = "serializers-code-gen"
  end
end
