# frozen_string_literal: true

module Panko
  # Nested (not scoped +Panko::CodeGen+) form on purpose: this file is
  # loaded first — both by the gem entrypoint and standalone by the
  # gemspec — so it must vivify +Panko+ itself; every other file then
  # reopens the namespace with the scoped form.
  module CodeGen
    VERSION = "0.1.0"

    # Generator name as it appears in user-facing artifacts. Spliced into the
    # +# Generated by ...+ line of every Dumped (and in-memory Compiled) file's
    # header banner, and into the synthetic backtrace path (compiler.rb).
    # Held as a single constant so both stay in sync.
    GENERATOR_NAME = "Panko::CodeGen"
  end
end
