version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "weekly"
    groups:
      docs-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "bundler"
    directory: "/gemfiles"
    schedule:
      interval: "weekly"
    groups:
      gemfiles-dependencies:
        patterns:
          - "*"
