# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - rubocop-performance
  - standard-performance
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - ext/**/*
    - gemfiles/**/*


Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  SafeAutoCorrect: true

# TODO: need to work on specs.
RSpec:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*