# frozen_string_literal: true

module SerializersCodeGen
  module Generators
    # Header banner emitter shared by +JsonMode+ and +HashMode+. Produces
    # the per-file comment block that follows +# frozen_string_literal:
    # true+ and precedes the first +class+ line, per
    # +docs/dumping.md § Dumped file shape+. Written once at the top of
    # every emit, never per inner class — multi-class trees show only the
    # root Descriptor in the +Descriptor:+ line because that's the
    # Descriptor +compile+ / +dump+ was called with.
    #
    # The bytes the banner produces are part of the
    # +Compile ≡ Dump byte-identical+ contract from
    # +CLAUDE.md § Architectural shape+ — the same banner appears in the
    # in-memory +module_eval+'d source (where it's invisible to
    # +Method#source_location+ but visible to +method_source+ retrieval)
    # and in the on-disk +.generated+ file, so reading either form
    # surfaces the same Descriptor / Mode / Config triple.
    module Banner
      # Appends the banner's lines to +builder+ in place, between the
      # +# frozen_string_literal: true+ pragma (already emitted) and the
      # first +class+ line (emitted by the caller's per-class loop). The
      # +#+-only separators bracket the identification block so the
      # banner reads as a self-contained header even when the +# To use:+
      # example sits next to the surrounding +class+ source.
      #
      # @param builder [SerializersCodeGen::CodeBuilder] target buffer at
      #   indent level 0; the caller has already appended the
      #   +# frozen_string_literal: true+ pragma followed by one blank
      #   line (the +Layout/EmptyLineAfterMagicComment+ standardrb shape
      #   the snapshot fixtures travel through), so the banner's first
      #   line is the +#+-only separator
      # @param descriptor [SerializersCodeGen::Descriptor] the root
      #   Descriptor for the emit — its +name+ feeds the +Descriptor:+
      #   line, the snake_case +require_relative+ basename, and the
      #   class-name in the +.new(descriptor: ...)+ example
      # @param output [Symbol] +:json+ or +:hash+ — feeds the +Mode:+
      #   line (with leading colon, e.g. +Mode: :json+) and selects the
      #   class-name suffix via {Compiler::OUTPUT_SUFFIXES}
      # @param config [SerializersCodeGen::Config] resolved settings;
      #   every field lands in the +Config:+ line in declaration order
      # @return [void]
      def self.emit(builder, descriptor, output:, config:)
        suffix = Compiler::OUTPUT_SUFFIXES.fetch(output)
        snake = descriptor.name.gsub(/(?<=.)([A-Z])/, '_\1').downcase
        builder.line "#"
        builder.line "# Generated by #{GENERATOR_NAME}"
        builder.line "# Descriptor: #{descriptor.name}"
        builder.line "# Mode: :#{output}"
        builder.line "# Config: #{render_config(config)}"
        builder.line "#"
        builder.line "# To use:"
        builder.line %(#   require_relative "#{snake}_#{output}.generated")
        builder.line "#   #{descriptor.name}_#{suffix}.new(descriptor: descriptor).serialize_one(record)"
        builder.blank
      end

      # Renders the +Config+ as a comma-separated +<key>=<value>+ list
      # in declaration order. Symbol values render with a leading colon
      # (e.g. +hash_record_key_type=:string+), Booleans render as
      # +true+ / +false+ — both via +Object#inspect+ which already
      # produces the documented shapes.
      #
      # @param config [SerializersCodeGen::Config]
      # @return [String] one-line +<key>=<value>, ...+ rendering
      def self.render_config(config)
        config.to_h.map { |k, v| "#{k}=#{v.inspect}" }.join(", ")
      end
      private_class_method :render_config
    end
  end
end
