# frozen_string_literal: true

module Panko::CodeGen
  module Generators
    module Banner
      def self.emit(builder, descriptor, output:, config:)
        suffix = Compiler::OUTPUT_SUFFIXES.fetch(output)
        snake = descriptor.name.gsub(/(?<=.)([A-Z])/, '_\1').downcase
        builder.line "#"
        builder.line "# Generated by #{GENERATOR_NAME}"
        builder.line "# Descriptor: #{descriptor.name}"
        builder.line "# Mode: :#{output}"
        builder.line "# Config: #{render_config(config)}"
        builder.line "#"
        builder.line "# To use:"
        builder.line %(#   require_relative "#{snake}_#{output}.generated")
        builder.line "#   #{descriptor.name}_#{suffix}.new(descriptor: descriptor).serialize_one(record)"
        builder.blank
      end

      def self.render_config(config)
        config.to_h.map { |k, v| "#{k}=#{v.inspect}" }.join(", ")
      end
      private_class_method :render_config
    end
  end
end
